services:
    # =========================
    # App - https://laravel.com
    # =========================
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.app.rule=Host(`app.localhost`)'
            - 'traefik.http.routers.app.entrypoints=web'
            - 'traefik.http.services.app.loadbalancer.server.port=80'

    # =========================
    # Traefik reverse proxy
    # src: https://doc.traefik.io/traefik/getting-started/docker
    # =========================
    traefik:
        image: traefik:v3.6
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--entrypoints.web.address=:80'
        ports:
            - '80:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - sail
        restart: always

    # =========================
    # PostgreSQL database
    # =========================
    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

    # =========================
    # pgAdmin database management tool
    # src: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    # =========================
    pgadmin:
        image: dpage/pgadmin4:9.12.0
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - pgsql
        networks:
            - sail
        volumes:
            - sail-pgadmin:/var/lib/pgadmin
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)'
            - 'traefik.http.routers.pgadmin.entrypoints=web'
            - 'traefik.http.services.pgadmin.loadbalancer.server.port=80'
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-pgadmin:
        driver: local
