apiVersion: batch/v1
kind: CronJob
metadata:
  name: posexei-scheduler
  namespace: posexei
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler
              image: posexei:latest
              command: ["php", "artisan", "schedule:run"]
              envFrom:
                - configMapRef:
                    name: posexei-config
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: posexei-secrets
                      key: db_password
          restartPolicy: OnFailure
