apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceId"\s*:\s*"([a-f0-9]{32})"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "Open in Tempo"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToLogs:
        datasourceUid: loki
        tags: [{ key: "service.name", value: "service" }]
        filterByTraceID: true
        filterBySpanID: false
        mapTagNamesEnabled: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: "service.name", value: "service" }]
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
