apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: posexei-ingress
  namespace: posexei
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: posexei.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: posexei-web
                port:
                  number: 80
