apiVersion: apps/v1
kind: Deployment
metadata:
  name: posexei-web
  namespace: posexei
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posexei-web
  template:
    metadata:
      labels:
        app: posexei-web
    spec:
      containers:
        - name: php
          image: posexei:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: posexei-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posexei-secrets
                  key: db_password
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        - name: traefik
          image: traefik:v3.6
          args:
            - "--api.insecure=true"
            - "--providers.file.filename=/etc/traefik/traefik-config.yaml"
            - "--entrypoints.web.address=:80"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: traefik-config
              mountPath: /etc/traefik
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

      volumes:
        - name: traefik-config
          configMap:
            name: posexei-traefik-config
