loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: s3
    s3:
      region: us-east-1
      bucketnames: loki-storage-bucket # To be replaced with actual terraform output
  schema_config:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

gateway:
  enabled: true
