apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: posexei
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
        spike_limit_mib: 200
      resourcedetection:
        detectors: [env, eks, system]

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlphttp/loki:
        endpoint: "http://loki-gateway.posexei.svc.cluster.local/otlp"
      otlp/tempo:
        endpoint: "tempo-distributor.posexei.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [resourcedetection, memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [resourcedetection, memory_limiter, batch]
          exporters: [otlphttp/loki]
        traces:
          receivers: [otlp]
          processors: [resourcedetection, memory_limiter, batch]
          exporters: [otlp/tempo]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: posexei
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: prometheus
      port: 8889
      targetPort: 8889
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: posexei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          command:
            - "/otelcol-contrib"
            - "--config=/conf/otel-collector-config.yaml"
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 8889
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-conf
